name: proyek2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  flutter_secure_storage: ^7.0.0
  shared_preferences: ^2.0.15
  data_table_2: ^2.5.0
  file_picker: ^5.3.0
  intl: ^0.18.0
  pdf: ^3.6.0
  html: ^0.15.5
  printing: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/logo.png
