name: proyek2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.0.15
  data_table_2: ^2.5.0
  intl: ^0.18.0
  pdf: ^3.10.2
  html: ^0.15.5
  printing: ^5.6.0  
  flutter_plugin_android_lifecycle: ^2.0.6
  image_picker: ^1.1.2
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/logo.png
  - assets/100k.png
  - assets/50k.png
  - assets/20k.png
  - assets/10k.png
  - assets/5k.png
  - assets/2k.png
  - assets/1k.png
  - assets/500p.png
  - assets/200p.jpg
  - assets/100p.jpg
